#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCuaHangTienLoi.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CuaHangTienLoiOnline")]
	public partial class dbQLCuaHangTienLoiDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertbaiViet(baiViet instance);
    partial void UpdatebaiViet(baiViet instance);
    partial void DeletebaiViet(baiViet instance);
    partial void InserttaiKhoanTV(taiKhoanTV instance);
    partial void UpdatetaiKhoanTV(taiKhoanTV instance);
    partial void DeletetaiKhoanTV(taiKhoanTV instance);
    partial void InsertctDonHang(ctDonHang instance);
    partial void UpdatectDonHang(ctDonHang instance);
    partial void DeletectDonHang(ctDonHang instance);
    partial void InsertdonHang(donHang instance);
    partial void UpdatedonHang(donHang instance);
    partial void DeletedonHang(donHang instance);
    partial void InsertkhachHang(khachHang instance);
    partial void UpdatekhachHang(khachHang instance);
    partial void DeletekhachHang(khachHang instance);
    partial void InsertloaiSanPham(loaiSanPham instance);
    partial void UpdateloaiSanPham(loaiSanPham instance);
    partial void DeleteloaiSanPham(loaiSanPham instance);
    partial void InsertnhomTk(nhomTk instance);
    partial void UpdatenhomTk(nhomTk instance);
    partial void DeletenhomTk(nhomTk instance);
    partial void InsertquanHuyen(quanHuyen instance);
    partial void UpdatequanHuyen(quanHuyen instance);
    partial void DeletequanHuyen(quanHuyen instance);
    partial void InsertsanPham(sanPham instance);
    partial void UpdatesanPham(sanPham instance);
    partial void DeletesanPham(sanPham instance);
    #endregion
		
		public dbQLCuaHangTienLoiDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["CuaHangTienLoiOnlineConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbQLCuaHangTienLoiDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQLCuaHangTienLoiDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQLCuaHangTienLoiDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQLCuaHangTienLoiDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<baiViet> baiViets
		{
			get
			{
				return this.GetTable<baiViet>();
			}
		}
		
		public System.Data.Linq.Table<taiKhoanTV> taiKhoanTVs
		{
			get
			{
				return this.GetTable<taiKhoanTV>();
			}
		}
		
		public System.Data.Linq.Table<ctDonHang> ctDonHangs
		{
			get
			{
				return this.GetTable<ctDonHang>();
			}
		}
		
		public System.Data.Linq.Table<donHang> donHangs
		{
			get
			{
				return this.GetTable<donHang>();
			}
		}
		
		public System.Data.Linq.Table<khachHang> khachHangs
		{
			get
			{
				return this.GetTable<khachHang>();
			}
		}
		
		public System.Data.Linq.Table<loaiSanPham> loaiSanPhams
		{
			get
			{
				return this.GetTable<loaiSanPham>();
			}
		}
		
		public System.Data.Linq.Table<nhomTk> nhomTks
		{
			get
			{
				return this.GetTable<nhomTk>();
			}
		}
		
		public System.Data.Linq.Table<quanHuyen> quanHuyens
		{
			get
			{
				return this.GetTable<quanHuyen>();
			}
		}
		
		public System.Data.Linq.Table<sanPham> sanPhams
		{
			get
			{
				return this.GetTable<sanPham>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.baiViet")]
	public partial class baiViet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maBV;
		
		private string _tenBV;
		
		private string _hinhDD;
		
		private string _ndTomTat;
		
		private System.Nullable<System.DateTime> _ngayDang;
		
		private string _noiDung;
		
		private string _taiKhoan;
		
		private System.Nullable<bool> _daDuyet;
		
		private System.Nullable<int> _maLoai;
		
		private EntityRef<taiKhoanTV> _taiKhoanTV;
		
		private EntityRef<loaiSanPham> _loaiSanPham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaBVChanging(string value);
    partial void OnmaBVChanged();
    partial void OntenBVChanging(string value);
    partial void OntenBVChanged();
    partial void OnhinhDDChanging(string value);
    partial void OnhinhDDChanged();
    partial void OnndTomTatChanging(string value);
    partial void OnndTomTatChanged();
    partial void OnngayDangChanging(System.Nullable<System.DateTime> value);
    partial void OnngayDangChanged();
    partial void OnnoiDungChanging(string value);
    partial void OnnoiDungChanged();
    partial void OntaiKhoanChanging(string value);
    partial void OntaiKhoanChanged();
    partial void OndaDuyetChanging(System.Nullable<bool> value);
    partial void OndaDuyetChanged();
    partial void OnmaLoaiChanging(System.Nullable<int> value);
    partial void OnmaLoaiChanged();
    #endregion
		
		public baiViet()
		{
			this._taiKhoanTV = default(EntityRef<taiKhoanTV>);
			this._loaiSanPham = default(EntityRef<loaiSanPham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maBV", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maBV
		{
			get
			{
				return this._maBV;
			}
			set
			{
				if ((this._maBV != value))
				{
					this.OnmaBVChanging(value);
					this.SendPropertyChanging();
					this._maBV = value;
					this.SendPropertyChanged("maBV");
					this.OnmaBVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenBV", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string tenBV
		{
			get
			{
				return this._tenBV;
			}
			set
			{
				if ((this._tenBV != value))
				{
					this.OntenBVChanging(value);
					this.SendPropertyChanging();
					this._tenBV = value;
					this.SendPropertyChanged("tenBV");
					this.OntenBVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hinhDD", DbType="VarChar(MAX)")]
		public string hinhDD
		{
			get
			{
				return this._hinhDD;
			}
			set
			{
				if ((this._hinhDD != value))
				{
					this.OnhinhDDChanging(value);
					this.SendPropertyChanging();
					this._hinhDD = value;
					this.SendPropertyChanged("hinhDD");
					this.OnhinhDDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ndTomTat", DbType="NVarChar(2000)")]
		public string ndTomTat
		{
			get
			{
				return this._ndTomTat;
			}
			set
			{
				if ((this._ndTomTat != value))
				{
					this.OnndTomTatChanging(value);
					this.SendPropertyChanging();
					this._ndTomTat = value;
					this.SendPropertyChanged("ndTomTat");
					this.OnndTomTatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayDang", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayDang
		{
			get
			{
				return this._ngayDang;
			}
			set
			{
				if ((this._ngayDang != value))
				{
					this.OnngayDangChanging(value);
					this.SendPropertyChanging();
					this._ngayDang = value;
					this.SendPropertyChanged("ngayDang");
					this.OnngayDangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noiDung", DbType="NVarChar(4000)")]
		public string noiDung
		{
			get
			{
				return this._noiDung;
			}
			set
			{
				if ((this._noiDung != value))
				{
					this.OnnoiDungChanging(value);
					this.SendPropertyChanging();
					this._noiDung = value;
					this.SendPropertyChanged("noiDung");
					this.OnnoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taiKhoan", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string taiKhoan
		{
			get
			{
				return this._taiKhoan;
			}
			set
			{
				if ((this._taiKhoan != value))
				{
					if (this._taiKhoanTV.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OntaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._taiKhoan = value;
					this.SendPropertyChanged("taiKhoan");
					this.OntaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_daDuyet", DbType="Bit")]
		public System.Nullable<bool> daDuyet
		{
			get
			{
				return this._daDuyet;
			}
			set
			{
				if ((this._daDuyet != value))
				{
					this.OndaDuyetChanging(value);
					this.SendPropertyChanging();
					this._daDuyet = value;
					this.SendPropertyChanged("daDuyet");
					this.OndaDuyetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLoai", DbType="Int")]
		public System.Nullable<int> maLoai
		{
			get
			{
				return this._maLoai;
			}
			set
			{
				if ((this._maLoai != value))
				{
					if (this._loaiSanPham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaLoaiChanging(value);
					this.SendPropertyChanging();
					this._maLoai = value;
					this.SendPropertyChanged("maLoai");
					this.OnmaLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="taiKhoanTV_baiViet", Storage="_taiKhoanTV", ThisKey="taiKhoan", OtherKey="taiKhoan", IsForeignKey=true)]
		public taiKhoanTV taiKhoanTV
		{
			get
			{
				return this._taiKhoanTV.Entity;
			}
			set
			{
				taiKhoanTV previousValue = this._taiKhoanTV.Entity;
				if (((previousValue != value) 
							|| (this._taiKhoanTV.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._taiKhoanTV.Entity = null;
						previousValue.baiViets.Remove(this);
					}
					this._taiKhoanTV.Entity = value;
					if ((value != null))
					{
						value.baiViets.Add(this);
						this._taiKhoan = value.taiKhoan;
					}
					else
					{
						this._taiKhoan = default(string);
					}
					this.SendPropertyChanged("taiKhoanTV");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="loaiSanPham_baiViet", Storage="_loaiSanPham", ThisKey="maLoai", OtherKey="maLoai", IsForeignKey=true)]
		public loaiSanPham loaiSanPham
		{
			get
			{
				return this._loaiSanPham.Entity;
			}
			set
			{
				loaiSanPham previousValue = this._loaiSanPham.Entity;
				if (((previousValue != value) 
							|| (this._loaiSanPham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._loaiSanPham.Entity = null;
						previousValue.baiViets.Remove(this);
					}
					this._loaiSanPham.Entity = value;
					if ((value != null))
					{
						value.baiViets.Add(this);
						this._maLoai = value.maLoai;
					}
					else
					{
						this._maLoai = default(Nullable<int>);
					}
					this.SendPropertyChanged("loaiSanPham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.taiKhoanTV")]
	public partial class taiKhoanTV : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _taiKhoan;
		
		private string _matKhau;
		
		private string _hoDem;
		
		private string _tenTV;
		
		private System.Nullable<System.DateTime> _ngaysinh;
		
		private System.Nullable<bool> _gioiTinh;
		
		private string _soDT;
		
		private string _email;
		
		private string _diaChi;
		
		private System.Nullable<bool> _trangThai;
		
		private string _ghiChu;
		
		private System.Nullable<int> _maNhom;
		
		private System.Nullable<int> _maQH;
		
		private EntitySet<baiViet> _baiViets;
		
		private EntitySet<donHang> _donHangs;
		
		private EntitySet<sanPham> _sanPhams;
		
		private EntityRef<nhomTk> _nhomTk;
		
		private EntityRef<quanHuyen> _quanHuyen;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OntaiKhoanChanging(string value);
    partial void OntaiKhoanChanged();
    partial void OnmatKhauChanging(string value);
    partial void OnmatKhauChanged();
    partial void OnhoDemChanging(string value);
    partial void OnhoDemChanged();
    partial void OntenTVChanging(string value);
    partial void OntenTVChanged();
    partial void OnngaysinhChanging(System.Nullable<System.DateTime> value);
    partial void OnngaysinhChanged();
    partial void OngioiTinhChanging(System.Nullable<bool> value);
    partial void OngioiTinhChanged();
    partial void OnsoDTChanging(string value);
    partial void OnsoDTChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OndiaChiChanging(string value);
    partial void OndiaChiChanged();
    partial void OntrangThaiChanging(System.Nullable<bool> value);
    partial void OntrangThaiChanged();
    partial void OnghiChuChanging(string value);
    partial void OnghiChuChanged();
    partial void OnmaNhomChanging(System.Nullable<int> value);
    partial void OnmaNhomChanged();
    partial void OnmaQHChanging(System.Nullable<int> value);
    partial void OnmaQHChanged();
    #endregion
		
		public taiKhoanTV()
		{
			this._baiViets = new EntitySet<baiViet>(new Action<baiViet>(this.attach_baiViets), new Action<baiViet>(this.detach_baiViets));
			this._donHangs = new EntitySet<donHang>(new Action<donHang>(this.attach_donHangs), new Action<donHang>(this.detach_donHangs));
			this._sanPhams = new EntitySet<sanPham>(new Action<sanPham>(this.attach_sanPhams), new Action<sanPham>(this.detach_sanPhams));
			this._nhomTk = default(EntityRef<nhomTk>);
			this._quanHuyen = default(EntityRef<quanHuyen>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taiKhoan", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string taiKhoan
		{
			get
			{
				return this._taiKhoan;
			}
			set
			{
				if ((this._taiKhoan != value))
				{
					this.OntaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._taiKhoan = value;
					this.SendPropertyChanged("taiKhoan");
					this.OntaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matKhau", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string matKhau
		{
			get
			{
				return this._matKhau;
			}
			set
			{
				if ((this._matKhau != value))
				{
					this.OnmatKhauChanging(value);
					this.SendPropertyChanging();
					this._matKhau = value;
					this.SendPropertyChanged("matKhau");
					this.OnmatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoDem", DbType="NVarChar(50)")]
		public string hoDem
		{
			get
			{
				return this._hoDem;
			}
			set
			{
				if ((this._hoDem != value))
				{
					this.OnhoDemChanging(value);
					this.SendPropertyChanging();
					this._hoDem = value;
					this.SendPropertyChanged("hoDem");
					this.OnhoDemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenTV", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string tenTV
		{
			get
			{
				return this._tenTV;
			}
			set
			{
				if ((this._tenTV != value))
				{
					this.OntenTVChanging(value);
					this.SendPropertyChanging();
					this._tenTV = value;
					this.SendPropertyChanged("tenTV");
					this.OntenTVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaysinh", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaysinh
		{
			get
			{
				return this._ngaysinh;
			}
			set
			{
				if ((this._ngaysinh != value))
				{
					this.OnngaysinhChanging(value);
					this.SendPropertyChanging();
					this._ngaysinh = value;
					this.SendPropertyChanged("ngaysinh");
					this.OnngaysinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioiTinh", DbType="Bit")]
		public System.Nullable<bool> gioiTinh
		{
			get
			{
				return this._gioiTinh;
			}
			set
			{
				if ((this._gioiTinh != value))
				{
					this.OngioiTinhChanging(value);
					this.SendPropertyChanging();
					this._gioiTinh = value;
					this.SendPropertyChanged("gioiTinh");
					this.OngioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soDT", DbType="NVarChar(20)")]
		public string soDT
		{
			get
			{
				return this._soDT;
			}
			set
			{
				if ((this._soDT != value))
				{
					this.OnsoDTChanging(value);
					this.SendPropertyChanging();
					this._soDT = value;
					this.SendPropertyChanged("soDT");
					this.OnsoDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaChi", DbType="NVarChar(250)")]
		public string diaChi
		{
			get
			{
				return this._diaChi;
			}
			set
			{
				if ((this._diaChi != value))
				{
					this.OndiaChiChanging(value);
					this.SendPropertyChanging();
					this._diaChi = value;
					this.SendPropertyChanged("diaChi");
					this.OndiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangThai", DbType="Bit")]
		public System.Nullable<bool> trangThai
		{
			get
			{
				return this._trangThai;
			}
			set
			{
				if ((this._trangThai != value))
				{
					this.OntrangThaiChanging(value);
					this.SendPropertyChanging();
					this._trangThai = value;
					this.SendPropertyChanged("trangThai");
					this.OntrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghiChu", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string ghiChu
		{
			get
			{
				return this._ghiChu;
			}
			set
			{
				if ((this._ghiChu != value))
				{
					this.OnghiChuChanging(value);
					this.SendPropertyChanging();
					this._ghiChu = value;
					this.SendPropertyChanged("ghiChu");
					this.OnghiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNhom", DbType="Int")]
		public System.Nullable<int> maNhom
		{
			get
			{
				return this._maNhom;
			}
			set
			{
				if ((this._maNhom != value))
				{
					if (this._nhomTk.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNhomChanging(value);
					this.SendPropertyChanging();
					this._maNhom = value;
					this.SendPropertyChanged("maNhom");
					this.OnmaNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maQH", DbType="Int")]
		public System.Nullable<int> maQH
		{
			get
			{
				return this._maQH;
			}
			set
			{
				if ((this._maQH != value))
				{
					if (this._quanHuyen.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaQHChanging(value);
					this.SendPropertyChanging();
					this._maQH = value;
					this.SendPropertyChanged("maQH");
					this.OnmaQHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="taiKhoanTV_baiViet", Storage="_baiViets", ThisKey="taiKhoan", OtherKey="taiKhoan")]
		public EntitySet<baiViet> baiViets
		{
			get
			{
				return this._baiViets;
			}
			set
			{
				this._baiViets.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="taiKhoanTV_donHang", Storage="_donHangs", ThisKey="taiKhoan", OtherKey="taiKhoan")]
		public EntitySet<donHang> donHangs
		{
			get
			{
				return this._donHangs;
			}
			set
			{
				this._donHangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="taiKhoanTV_sanPham", Storage="_sanPhams", ThisKey="taiKhoan", OtherKey="taiKhoan")]
		public EntitySet<sanPham> sanPhams
		{
			get
			{
				return this._sanPhams;
			}
			set
			{
				this._sanPhams.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhomTk_taiKhoanTV", Storage="_nhomTk", ThisKey="maNhom", OtherKey="maNhom", IsForeignKey=true)]
		public nhomTk nhomTk
		{
			get
			{
				return this._nhomTk.Entity;
			}
			set
			{
				nhomTk previousValue = this._nhomTk.Entity;
				if (((previousValue != value) 
							|| (this._nhomTk.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nhomTk.Entity = null;
						previousValue.taiKhoanTVs.Remove(this);
					}
					this._nhomTk.Entity = value;
					if ((value != null))
					{
						value.taiKhoanTVs.Add(this);
						this._maNhom = value.maNhom;
					}
					else
					{
						this._maNhom = default(Nullable<int>);
					}
					this.SendPropertyChanged("nhomTk");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="quanHuyen_taiKhoanTV", Storage="_quanHuyen", ThisKey="maQH", OtherKey="maQH", IsForeignKey=true)]
		public quanHuyen quanHuyen
		{
			get
			{
				return this._quanHuyen.Entity;
			}
			set
			{
				quanHuyen previousValue = this._quanHuyen.Entity;
				if (((previousValue != value) 
							|| (this._quanHuyen.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._quanHuyen.Entity = null;
						previousValue.taiKhoanTVs.Remove(this);
					}
					this._quanHuyen.Entity = value;
					if ((value != null))
					{
						value.taiKhoanTVs.Add(this);
						this._maQH = value.maQH;
					}
					else
					{
						this._maQH = default(Nullable<int>);
					}
					this.SendPropertyChanged("quanHuyen");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_baiViets(baiViet entity)
		{
			this.SendPropertyChanging();
			entity.taiKhoanTV = this;
		}
		
		private void detach_baiViets(baiViet entity)
		{
			this.SendPropertyChanging();
			entity.taiKhoanTV = null;
		}
		
		private void attach_donHangs(donHang entity)
		{
			this.SendPropertyChanging();
			entity.taiKhoanTV = this;
		}
		
		private void detach_donHangs(donHang entity)
		{
			this.SendPropertyChanging();
			entity.taiKhoanTV = null;
		}
		
		private void attach_sanPhams(sanPham entity)
		{
			this.SendPropertyChanging();
			entity.taiKhoanTV = this;
		}
		
		private void detach_sanPhams(sanPham entity)
		{
			this.SendPropertyChanging();
			entity.taiKhoanTV = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ctDonHang")]
	public partial class ctDonHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _soDH;
		
		private string _maSP;
		
		private System.Nullable<int> _soLuong;
		
		private System.Nullable<long> _giaBan;
		
		private System.Nullable<long> _giamGia;
		
		private EntityRef<donHang> _donHang;
		
		private EntityRef<sanPham> _sanPham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsoDHChanging(string value);
    partial void OnsoDHChanged();
    partial void OnmaSPChanging(string value);
    partial void OnmaSPChanged();
    partial void OnsoLuongChanging(System.Nullable<int> value);
    partial void OnsoLuongChanged();
    partial void OngiaBanChanging(System.Nullable<long> value);
    partial void OngiaBanChanged();
    partial void OngiamGiaChanging(System.Nullable<long> value);
    partial void OngiamGiaChanged();
    #endregion
		
		public ctDonHang()
		{
			this._donHang = default(EntityRef<donHang>);
			this._sanPham = default(EntityRef<sanPham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soDH", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string soDH
		{
			get
			{
				return this._soDH;
			}
			set
			{
				if ((this._soDH != value))
				{
					if (this._donHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnsoDHChanging(value);
					this.SendPropertyChanging();
					this._soDH = value;
					this.SendPropertyChanged("soDH");
					this.OnsoDHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maSP", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maSP
		{
			get
			{
				return this._maSP;
			}
			set
			{
				if ((this._maSP != value))
				{
					if (this._sanPham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaSPChanging(value);
					this.SendPropertyChanging();
					this._maSP = value;
					this.SendPropertyChanged("maSP");
					this.OnmaSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLuong", DbType="Int")]
		public System.Nullable<int> soLuong
		{
			get
			{
				return this._soLuong;
			}
			set
			{
				if ((this._soLuong != value))
				{
					this.OnsoLuongChanging(value);
					this.SendPropertyChanging();
					this._soLuong = value;
					this.SendPropertyChanged("soLuong");
					this.OnsoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giaBan", DbType="BigInt")]
		public System.Nullable<long> giaBan
		{
			get
			{
				return this._giaBan;
			}
			set
			{
				if ((this._giaBan != value))
				{
					this.OngiaBanChanging(value);
					this.SendPropertyChanging();
					this._giaBan = value;
					this.SendPropertyChanged("giaBan");
					this.OngiaBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giamGia", DbType="BigInt")]
		public System.Nullable<long> giamGia
		{
			get
			{
				return this._giamGia;
			}
			set
			{
				if ((this._giamGia != value))
				{
					this.OngiamGiaChanging(value);
					this.SendPropertyChanging();
					this._giamGia = value;
					this.SendPropertyChanged("giamGia");
					this.OngiamGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="donHang_ctDonHang", Storage="_donHang", ThisKey="soDH", OtherKey="soDH", IsForeignKey=true)]
		public donHang donHang
		{
			get
			{
				return this._donHang.Entity;
			}
			set
			{
				donHang previousValue = this._donHang.Entity;
				if (((previousValue != value) 
							|| (this._donHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._donHang.Entity = null;
						previousValue.ctDonHangs.Remove(this);
					}
					this._donHang.Entity = value;
					if ((value != null))
					{
						value.ctDonHangs.Add(this);
						this._soDH = value.soDH;
					}
					else
					{
						this._soDH = default(string);
					}
					this.SendPropertyChanged("donHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sanPham_ctDonHang", Storage="_sanPham", ThisKey="maSP", OtherKey="maSP", IsForeignKey=true)]
		public sanPham sanPham
		{
			get
			{
				return this._sanPham.Entity;
			}
			set
			{
				sanPham previousValue = this._sanPham.Entity;
				if (((previousValue != value) 
							|| (this._sanPham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._sanPham.Entity = null;
						previousValue.ctDonHangs.Remove(this);
					}
					this._sanPham.Entity = value;
					if ((value != null))
					{
						value.ctDonHangs.Add(this);
						this._maSP = value.maSP;
					}
					else
					{
						this._maSP = default(string);
					}
					this.SendPropertyChanged("sanPham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.donHang")]
	public partial class donHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _soDH;
		
		private string _maKH;
		
		private string _taiKhoan;
		
		private System.Nullable<System.DateTime> _ngayDat;
		
		private System.Nullable<bool> _daKichHoat;
		
		private System.Nullable<System.DateTime> _ngayGH;
		
		private string _diaChiGH;
		
		private string _ghiChu;
		
		private EntitySet<ctDonHang> _ctDonHangs;
		
		private EntityRef<taiKhoanTV> _taiKhoanTV;
		
		private EntityRef<khachHang> _khachHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsoDHChanging(string value);
    partial void OnsoDHChanged();
    partial void OnmaKHChanging(string value);
    partial void OnmaKHChanged();
    partial void OntaiKhoanChanging(string value);
    partial void OntaiKhoanChanged();
    partial void OnngayDatChanging(System.Nullable<System.DateTime> value);
    partial void OnngayDatChanged();
    partial void OndaKichHoatChanging(System.Nullable<bool> value);
    partial void OndaKichHoatChanged();
    partial void OnngayGHChanging(System.Nullable<System.DateTime> value);
    partial void OnngayGHChanged();
    partial void OndiaChiGHChanging(string value);
    partial void OndiaChiGHChanged();
    partial void OnghiChuChanging(string value);
    partial void OnghiChuChanged();
    #endregion
		
		public donHang()
		{
			this._ctDonHangs = new EntitySet<ctDonHang>(new Action<ctDonHang>(this.attach_ctDonHangs), new Action<ctDonHang>(this.detach_ctDonHangs));
			this._taiKhoanTV = default(EntityRef<taiKhoanTV>);
			this._khachHang = default(EntityRef<khachHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soDH", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string soDH
		{
			get
			{
				return this._soDH;
			}
			set
			{
				if ((this._soDH != value))
				{
					this.OnsoDHChanging(value);
					this.SendPropertyChanging();
					this._soDH = value;
					this.SendPropertyChanged("soDH");
					this.OnsoDHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKH", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string maKH
		{
			get
			{
				return this._maKH;
			}
			set
			{
				if ((this._maKH != value))
				{
					if (this._khachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaKHChanging(value);
					this.SendPropertyChanging();
					this._maKH = value;
					this.SendPropertyChanged("maKH");
					this.OnmaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taiKhoan", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string taiKhoan
		{
			get
			{
				return this._taiKhoan;
			}
			set
			{
				if ((this._taiKhoan != value))
				{
					if (this._taiKhoanTV.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OntaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._taiKhoan = value;
					this.SendPropertyChanged("taiKhoan");
					this.OntaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayDat", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayDat
		{
			get
			{
				return this._ngayDat;
			}
			set
			{
				if ((this._ngayDat != value))
				{
					this.OnngayDatChanging(value);
					this.SendPropertyChanging();
					this._ngayDat = value;
					this.SendPropertyChanged("ngayDat");
					this.OnngayDatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_daKichHoat", DbType="Bit")]
		public System.Nullable<bool> daKichHoat
		{
			get
			{
				return this._daKichHoat;
			}
			set
			{
				if ((this._daKichHoat != value))
				{
					this.OndaKichHoatChanging(value);
					this.SendPropertyChanging();
					this._daKichHoat = value;
					this.SendPropertyChanged("daKichHoat");
					this.OndaKichHoatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayGH", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayGH
		{
			get
			{
				return this._ngayGH;
			}
			set
			{
				if ((this._ngayGH != value))
				{
					this.OnngayGHChanging(value);
					this.SendPropertyChanging();
					this._ngayGH = value;
					this.SendPropertyChanged("ngayGH");
					this.OnngayGHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaChiGH", DbType="NVarChar(250)")]
		public string diaChiGH
		{
			get
			{
				return this._diaChiGH;
			}
			set
			{
				if ((this._diaChiGH != value))
				{
					this.OndiaChiGHChanging(value);
					this.SendPropertyChanging();
					this._diaChiGH = value;
					this.SendPropertyChanged("diaChiGH");
					this.OndiaChiGHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghiChu", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string ghiChu
		{
			get
			{
				return this._ghiChu;
			}
			set
			{
				if ((this._ghiChu != value))
				{
					this.OnghiChuChanging(value);
					this.SendPropertyChanging();
					this._ghiChu = value;
					this.SendPropertyChanged("ghiChu");
					this.OnghiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="donHang_ctDonHang", Storage="_ctDonHangs", ThisKey="soDH", OtherKey="soDH")]
		public EntitySet<ctDonHang> ctDonHangs
		{
			get
			{
				return this._ctDonHangs;
			}
			set
			{
				this._ctDonHangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="taiKhoanTV_donHang", Storage="_taiKhoanTV", ThisKey="taiKhoan", OtherKey="taiKhoan", IsForeignKey=true)]
		public taiKhoanTV taiKhoanTV
		{
			get
			{
				return this._taiKhoanTV.Entity;
			}
			set
			{
				taiKhoanTV previousValue = this._taiKhoanTV.Entity;
				if (((previousValue != value) 
							|| (this._taiKhoanTV.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._taiKhoanTV.Entity = null;
						previousValue.donHangs.Remove(this);
					}
					this._taiKhoanTV.Entity = value;
					if ((value != null))
					{
						value.donHangs.Add(this);
						this._taiKhoan = value.taiKhoan;
					}
					else
					{
						this._taiKhoan = default(string);
					}
					this.SendPropertyChanged("taiKhoanTV");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khachHang_donHang", Storage="_khachHang", ThisKey="maKH", OtherKey="maKH", IsForeignKey=true)]
		public khachHang khachHang
		{
			get
			{
				return this._khachHang.Entity;
			}
			set
			{
				khachHang previousValue = this._khachHang.Entity;
				if (((previousValue != value) 
							|| (this._khachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._khachHang.Entity = null;
						previousValue.donHangs.Remove(this);
					}
					this._khachHang.Entity = value;
					if ((value != null))
					{
						value.donHangs.Add(this);
						this._maKH = value.maKH;
					}
					else
					{
						this._maKH = default(string);
					}
					this.SendPropertyChanged("khachHang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ctDonHangs(ctDonHang entity)
		{
			this.SendPropertyChanging();
			entity.donHang = this;
		}
		
		private void detach_ctDonHangs(ctDonHang entity)
		{
			this.SendPropertyChanging();
			entity.donHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.khachHang")]
	public partial class khachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maKH;
		
		private string _tenKH;
		
		private string _soDT;
		
		private string _email;
		
		private string _diaChi;
		
		private System.Nullable<System.DateTime> _ngaySinh;
		
		private System.Nullable<bool> _gioiTinh;
		
		private string _ghiChu;
		
		private System.Nullable<int> _maQH;
		
		private EntitySet<donHang> _donHangs;
		
		private EntityRef<quanHuyen> _quanHuyen;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaKHChanging(string value);
    partial void OnmaKHChanged();
    partial void OntenKHChanging(string value);
    partial void OntenKHChanged();
    partial void OnsoDTChanging(string value);
    partial void OnsoDTChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OndiaChiChanging(string value);
    partial void OndiaChiChanged();
    partial void OnngaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnngaySinhChanged();
    partial void OngioiTinhChanging(System.Nullable<bool> value);
    partial void OngioiTinhChanged();
    partial void OnghiChuChanging(string value);
    partial void OnghiChuChanged();
    partial void OnmaQHChanging(System.Nullable<int> value);
    partial void OnmaQHChanged();
    #endregion
		
		public khachHang()
		{
			this._donHangs = new EntitySet<donHang>(new Action<donHang>(this.attach_donHangs), new Action<donHang>(this.detach_donHangs));
			this._quanHuyen = default(EntityRef<quanHuyen>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKH", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maKH
		{
			get
			{
				return this._maKH;
			}
			set
			{
				if ((this._maKH != value))
				{
					this.OnmaKHChanging(value);
					this.SendPropertyChanging();
					this._maKH = value;
					this.SendPropertyChanged("maKH");
					this.OnmaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenKH", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tenKH
		{
			get
			{
				return this._tenKH;
			}
			set
			{
				if ((this._tenKH != value))
				{
					this.OntenKHChanging(value);
					this.SendPropertyChanging();
					this._tenKH = value;
					this.SendPropertyChanged("tenKH");
					this.OntenKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soDT", DbType="VarChar(20)")]
		public string soDT
		{
			get
			{
				return this._soDT;
			}
			set
			{
				if ((this._soDT != value))
				{
					this.OnsoDTChanging(value);
					this.SendPropertyChanging();
					this._soDT = value;
					this.SendPropertyChanged("soDT");
					this.OnsoDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaChi", DbType="NVarChar(250)")]
		public string diaChi
		{
			get
			{
				return this._diaChi;
			}
			set
			{
				if ((this._diaChi != value))
				{
					this.OndiaChiChanging(value);
					this.SendPropertyChanging();
					this._diaChi = value;
					this.SendPropertyChanged("diaChi");
					this.OndiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaySinh", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaySinh
		{
			get
			{
				return this._ngaySinh;
			}
			set
			{
				if ((this._ngaySinh != value))
				{
					this.OnngaySinhChanging(value);
					this.SendPropertyChanging();
					this._ngaySinh = value;
					this.SendPropertyChanged("ngaySinh");
					this.OnngaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioiTinh", DbType="Bit")]
		public System.Nullable<bool> gioiTinh
		{
			get
			{
				return this._gioiTinh;
			}
			set
			{
				if ((this._gioiTinh != value))
				{
					this.OngioiTinhChanging(value);
					this.SendPropertyChanging();
					this._gioiTinh = value;
					this.SendPropertyChanged("gioiTinh");
					this.OngioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghiChu", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string ghiChu
		{
			get
			{
				return this._ghiChu;
			}
			set
			{
				if ((this._ghiChu != value))
				{
					this.OnghiChuChanging(value);
					this.SendPropertyChanging();
					this._ghiChu = value;
					this.SendPropertyChanged("ghiChu");
					this.OnghiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maQH", DbType="Int")]
		public System.Nullable<int> maQH
		{
			get
			{
				return this._maQH;
			}
			set
			{
				if ((this._maQH != value))
				{
					if (this._quanHuyen.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaQHChanging(value);
					this.SendPropertyChanging();
					this._maQH = value;
					this.SendPropertyChanged("maQH");
					this.OnmaQHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khachHang_donHang", Storage="_donHangs", ThisKey="maKH", OtherKey="maKH")]
		public EntitySet<donHang> donHangs
		{
			get
			{
				return this._donHangs;
			}
			set
			{
				this._donHangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="quanHuyen_khachHang", Storage="_quanHuyen", ThisKey="maQH", OtherKey="maQH", IsForeignKey=true)]
		public quanHuyen quanHuyen
		{
			get
			{
				return this._quanHuyen.Entity;
			}
			set
			{
				quanHuyen previousValue = this._quanHuyen.Entity;
				if (((previousValue != value) 
							|| (this._quanHuyen.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._quanHuyen.Entity = null;
						previousValue.khachHangs.Remove(this);
					}
					this._quanHuyen.Entity = value;
					if ((value != null))
					{
						value.khachHangs.Add(this);
						this._maQH = value.maQH;
					}
					else
					{
						this._maQH = default(Nullable<int>);
					}
					this.SendPropertyChanged("quanHuyen");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_donHangs(donHang entity)
		{
			this.SendPropertyChanging();
			entity.khachHang = this;
		}
		
		private void detach_donHangs(donHang entity)
		{
			this.SendPropertyChanging();
			entity.khachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.loaiSanPham")]
	public partial class loaiSanPham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maLoai;
		
		private string _loaiSP;
		
		private string _ghiChu;
		
		private EntitySet<baiViet> _baiViets;
		
		private EntitySet<sanPham> _sanPhams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaLoaiChanging(int value);
    partial void OnmaLoaiChanged();
    partial void OnloaiSPChanging(string value);
    partial void OnloaiSPChanged();
    partial void OnghiChuChanging(string value);
    partial void OnghiChuChanged();
    #endregion
		
		public loaiSanPham()
		{
			this._baiViets = new EntitySet<baiViet>(new Action<baiViet>(this.attach_baiViets), new Action<baiViet>(this.detach_baiViets));
			this._sanPhams = new EntitySet<sanPham>(new Action<sanPham>(this.attach_sanPhams), new Action<sanPham>(this.detach_sanPhams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLoai", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maLoai
		{
			get
			{
				return this._maLoai;
			}
			set
			{
				if ((this._maLoai != value))
				{
					this.OnmaLoaiChanging(value);
					this.SendPropertyChanging();
					this._maLoai = value;
					this.SendPropertyChanged("maLoai");
					this.OnmaLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaiSP", DbType="NVarChar(88) NOT NULL", CanBeNull=false)]
		public string loaiSP
		{
			get
			{
				return this._loaiSP;
			}
			set
			{
				if ((this._loaiSP != value))
				{
					this.OnloaiSPChanging(value);
					this.SendPropertyChanging();
					this._loaiSP = value;
					this.SendPropertyChanged("loaiSP");
					this.OnloaiSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghiChu", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string ghiChu
		{
			get
			{
				return this._ghiChu;
			}
			set
			{
				if ((this._ghiChu != value))
				{
					this.OnghiChuChanging(value);
					this.SendPropertyChanging();
					this._ghiChu = value;
					this.SendPropertyChanged("ghiChu");
					this.OnghiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="loaiSanPham_baiViet", Storage="_baiViets", ThisKey="maLoai", OtherKey="maLoai")]
		public EntitySet<baiViet> baiViets
		{
			get
			{
				return this._baiViets;
			}
			set
			{
				this._baiViets.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="loaiSanPham_sanPham", Storage="_sanPhams", ThisKey="maLoai", OtherKey="maLoai")]
		public EntitySet<sanPham> sanPhams
		{
			get
			{
				return this._sanPhams;
			}
			set
			{
				this._sanPhams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_baiViets(baiViet entity)
		{
			this.SendPropertyChanging();
			entity.loaiSanPham = this;
		}
		
		private void detach_baiViets(baiViet entity)
		{
			this.SendPropertyChanging();
			entity.loaiSanPham = null;
		}
		
		private void attach_sanPhams(sanPham entity)
		{
			this.SendPropertyChanging();
			entity.loaiSanPham = this;
		}
		
		private void detach_sanPhams(sanPham entity)
		{
			this.SendPropertyChanging();
			entity.loaiSanPham = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nhomTk")]
	public partial class nhomTk : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maNhom;
		
		private string _tenNhom;
		
		private string _ghiChu;
		
		private EntitySet<taiKhoanTV> _taiKhoanTVs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaNhomChanging(int value);
    partial void OnmaNhomChanged();
    partial void OntenNhomChanging(string value);
    partial void OntenNhomChanged();
    partial void OnghiChuChanging(string value);
    partial void OnghiChuChanged();
    #endregion
		
		public nhomTk()
		{
			this._taiKhoanTVs = new EntitySet<taiKhoanTV>(new Action<taiKhoanTV>(this.attach_taiKhoanTVs), new Action<taiKhoanTV>(this.detach_taiKhoanTVs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNhom", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maNhom
		{
			get
			{
				return this._maNhom;
			}
			set
			{
				if ((this._maNhom != value))
				{
					this.OnmaNhomChanging(value);
					this.SendPropertyChanging();
					this._maNhom = value;
					this.SendPropertyChanged("maNhom");
					this.OnmaNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenNhom", DbType="NVarChar(35) NOT NULL", CanBeNull=false)]
		public string tenNhom
		{
			get
			{
				return this._tenNhom;
			}
			set
			{
				if ((this._tenNhom != value))
				{
					this.OntenNhomChanging(value);
					this.SendPropertyChanging();
					this._tenNhom = value;
					this.SendPropertyChanged("tenNhom");
					this.OntenNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghiChu", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string ghiChu
		{
			get
			{
				return this._ghiChu;
			}
			set
			{
				if ((this._ghiChu != value))
				{
					this.OnghiChuChanging(value);
					this.SendPropertyChanging();
					this._ghiChu = value;
					this.SendPropertyChanged("ghiChu");
					this.OnghiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhomTk_taiKhoanTV", Storage="_taiKhoanTVs", ThisKey="maNhom", OtherKey="maNhom")]
		public EntitySet<taiKhoanTV> taiKhoanTVs
		{
			get
			{
				return this._taiKhoanTVs;
			}
			set
			{
				this._taiKhoanTVs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_taiKhoanTVs(taiKhoanTV entity)
		{
			this.SendPropertyChanging();
			entity.nhomTk = this;
		}
		
		private void detach_taiKhoanTVs(taiKhoanTV entity)
		{
			this.SendPropertyChanging();
			entity.nhomTk = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.quanHuyen")]
	public partial class quanHuyen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maQH;
		
		private string _tenQH;
		
		private string _tinhThanh;
		
		private string _ghiChu;
		
		private EntitySet<taiKhoanTV> _taiKhoanTVs;
		
		private EntitySet<khachHang> _khachHangs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaQHChanging(int value);
    partial void OnmaQHChanged();
    partial void OntenQHChanging(string value);
    partial void OntenQHChanged();
    partial void OntinhThanhChanging(string value);
    partial void OntinhThanhChanged();
    partial void OnghiChuChanging(string value);
    partial void OnghiChuChanged();
    #endregion
		
		public quanHuyen()
		{
			this._taiKhoanTVs = new EntitySet<taiKhoanTV>(new Action<taiKhoanTV>(this.attach_taiKhoanTVs), new Action<taiKhoanTV>(this.detach_taiKhoanTVs));
			this._khachHangs = new EntitySet<khachHang>(new Action<khachHang>(this.attach_khachHangs), new Action<khachHang>(this.detach_khachHangs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maQH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maQH
		{
			get
			{
				return this._maQH;
			}
			set
			{
				if ((this._maQH != value))
				{
					this.OnmaQHChanging(value);
					this.SendPropertyChanging();
					this._maQH = value;
					this.SendPropertyChanged("maQH");
					this.OnmaQHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenQH", DbType="NVarChar(88) NOT NULL", CanBeNull=false)]
		public string tenQH
		{
			get
			{
				return this._tenQH;
			}
			set
			{
				if ((this._tenQH != value))
				{
					this.OntenQHChanging(value);
					this.SendPropertyChanging();
					this._tenQH = value;
					this.SendPropertyChanged("tenQH");
					this.OntenQHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tinhThanh", DbType="NVarChar(65) NOT NULL", CanBeNull=false)]
		public string tinhThanh
		{
			get
			{
				return this._tinhThanh;
			}
			set
			{
				if ((this._tinhThanh != value))
				{
					this.OntinhThanhChanging(value);
					this.SendPropertyChanging();
					this._tinhThanh = value;
					this.SendPropertyChanged("tinhThanh");
					this.OntinhThanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghiChu", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string ghiChu
		{
			get
			{
				return this._ghiChu;
			}
			set
			{
				if ((this._ghiChu != value))
				{
					this.OnghiChuChanging(value);
					this.SendPropertyChanging();
					this._ghiChu = value;
					this.SendPropertyChanged("ghiChu");
					this.OnghiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="quanHuyen_taiKhoanTV", Storage="_taiKhoanTVs", ThisKey="maQH", OtherKey="maQH")]
		public EntitySet<taiKhoanTV> taiKhoanTVs
		{
			get
			{
				return this._taiKhoanTVs;
			}
			set
			{
				this._taiKhoanTVs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="quanHuyen_khachHang", Storage="_khachHangs", ThisKey="maQH", OtherKey="maQH")]
		public EntitySet<khachHang> khachHangs
		{
			get
			{
				return this._khachHangs;
			}
			set
			{
				this._khachHangs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_taiKhoanTVs(taiKhoanTV entity)
		{
			this.SendPropertyChanging();
			entity.quanHuyen = this;
		}
		
		private void detach_taiKhoanTVs(taiKhoanTV entity)
		{
			this.SendPropertyChanging();
			entity.quanHuyen = null;
		}
		
		private void attach_khachHangs(khachHang entity)
		{
			this.SendPropertyChanging();
			entity.quanHuyen = this;
		}
		
		private void detach_khachHangs(khachHang entity)
		{
			this.SendPropertyChanging();
			entity.quanHuyen = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sanPham")]
	public partial class sanPham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maSP;
		
		private string _tenSP;
		
		private string _hinhDD;
		
		private string _ndTomTat;
		
		private System.Nullable<System.DateTime> _ngayDang;
		
		private string _loaiHang;
		
		private string _noiDung;
		
		private string _taiKhoan;
		
		private System.Nullable<bool> _daDuyet;
		
		private System.Nullable<int> _giaBan;
		
		private System.Nullable<int> _giamGia;
		
		private System.Nullable<int> _maLoai;
		
		private string _nhaSanXuat;
		
		private string _dvt;
		
		private EntitySet<ctDonHang> _ctDonHangs;
		
		private EntityRef<loaiSanPham> _loaiSanPham;
		
		private EntityRef<taiKhoanTV> _taiKhoanTV;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaSPChanging(string value);
    partial void OnmaSPChanged();
    partial void OntenSPChanging(string value);
    partial void OntenSPChanged();
    partial void OnhinhDDChanging(string value);
    partial void OnhinhDDChanged();
    partial void OnndTomTatChanging(string value);
    partial void OnndTomTatChanged();
    partial void OnngayDangChanging(System.Nullable<System.DateTime> value);
    partial void OnngayDangChanged();
    partial void OnloaiHangChanging(string value);
    partial void OnloaiHangChanged();
    partial void OnnoiDungChanging(string value);
    partial void OnnoiDungChanged();
    partial void OntaiKhoanChanging(string value);
    partial void OntaiKhoanChanged();
    partial void OndaDuyetChanging(System.Nullable<bool> value);
    partial void OndaDuyetChanged();
    partial void OngiaBanChanging(System.Nullable<int> value);
    partial void OngiaBanChanged();
    partial void OngiamGiaChanging(System.Nullable<int> value);
    partial void OngiamGiaChanged();
    partial void OnmaLoaiChanging(System.Nullable<int> value);
    partial void OnmaLoaiChanged();
    partial void OnnhaSanXuatChanging(string value);
    partial void OnnhaSanXuatChanged();
    partial void OndvtChanging(string value);
    partial void OndvtChanged();
    #endregion
		
		public sanPham()
		{
			this._ctDonHangs = new EntitySet<ctDonHang>(new Action<ctDonHang>(this.attach_ctDonHangs), new Action<ctDonHang>(this.detach_ctDonHangs));
			this._loaiSanPham = default(EntityRef<loaiSanPham>);
			this._taiKhoanTV = default(EntityRef<taiKhoanTV>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maSP", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maSP
		{
			get
			{
				return this._maSP;
			}
			set
			{
				if ((this._maSP != value))
				{
					this.OnmaSPChanging(value);
					this.SendPropertyChanging();
					this._maSP = value;
					this.SendPropertyChanged("maSP");
					this.OnmaSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenSP", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string tenSP
		{
			get
			{
				return this._tenSP;
			}
			set
			{
				if ((this._tenSP != value))
				{
					this.OntenSPChanging(value);
					this.SendPropertyChanging();
					this._tenSP = value;
					this.SendPropertyChanged("tenSP");
					this.OntenSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hinhDD", DbType="VarChar(MAX)")]
		public string hinhDD
		{
			get
			{
				return this._hinhDD;
			}
			set
			{
				if ((this._hinhDD != value))
				{
					this.OnhinhDDChanging(value);
					this.SendPropertyChanging();
					this._hinhDD = value;
					this.SendPropertyChanged("hinhDD");
					this.OnhinhDDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ndTomTat", DbType="NVarChar(2000)")]
		public string ndTomTat
		{
			get
			{
				return this._ndTomTat;
			}
			set
			{
				if ((this._ndTomTat != value))
				{
					this.OnndTomTatChanging(value);
					this.SendPropertyChanging();
					this._ndTomTat = value;
					this.SendPropertyChanged("ndTomTat");
					this.OnndTomTatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayDang", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayDang
		{
			get
			{
				return this._ngayDang;
			}
			set
			{
				if ((this._ngayDang != value))
				{
					this.OnngayDangChanging(value);
					this.SendPropertyChanging();
					this._ngayDang = value;
					this.SendPropertyChanged("ngayDang");
					this.OnngayDangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaiHang", DbType="NVarChar(30)")]
		public string loaiHang
		{
			get
			{
				return this._loaiHang;
			}
			set
			{
				if ((this._loaiHang != value))
				{
					this.OnloaiHangChanging(value);
					this.SendPropertyChanging();
					this._loaiHang = value;
					this.SendPropertyChanged("loaiHang");
					this.OnloaiHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noiDung", DbType="NVarChar(4000)")]
		public string noiDung
		{
			get
			{
				return this._noiDung;
			}
			set
			{
				if ((this._noiDung != value))
				{
					this.OnnoiDungChanging(value);
					this.SendPropertyChanging();
					this._noiDung = value;
					this.SendPropertyChanged("noiDung");
					this.OnnoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taiKhoan", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string taiKhoan
		{
			get
			{
				return this._taiKhoan;
			}
			set
			{
				if ((this._taiKhoan != value))
				{
					if (this._taiKhoanTV.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OntaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._taiKhoan = value;
					this.SendPropertyChanged("taiKhoan");
					this.OntaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_daDuyet", DbType="Bit")]
		public System.Nullable<bool> daDuyet
		{
			get
			{
				return this._daDuyet;
			}
			set
			{
				if ((this._daDuyet != value))
				{
					this.OndaDuyetChanging(value);
					this.SendPropertyChanging();
					this._daDuyet = value;
					this.SendPropertyChanged("daDuyet");
					this.OndaDuyetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giaBan", DbType="Int")]
		public System.Nullable<int> giaBan
		{
			get
			{
				return this._giaBan;
			}
			set
			{
				if ((this._giaBan != value))
				{
					this.OngiaBanChanging(value);
					this.SendPropertyChanging();
					this._giaBan = value;
					this.SendPropertyChanged("giaBan");
					this.OngiaBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giamGia", DbType="Int")]
		public System.Nullable<int> giamGia
		{
			get
			{
				return this._giamGia;
			}
			set
			{
				if ((this._giamGia != value))
				{
					this.OngiamGiaChanging(value);
					this.SendPropertyChanging();
					this._giamGia = value;
					this.SendPropertyChanged("giamGia");
					this.OngiamGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLoai", DbType="Int")]
		public System.Nullable<int> maLoai
		{
			get
			{
				return this._maLoai;
			}
			set
			{
				if ((this._maLoai != value))
				{
					if (this._loaiSanPham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaLoaiChanging(value);
					this.SendPropertyChanging();
					this._maLoai = value;
					this.SendPropertyChanged("maLoai");
					this.OnmaLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nhaSanXuat", DbType="NVarChar(89)")]
		public string nhaSanXuat
		{
			get
			{
				return this._nhaSanXuat;
			}
			set
			{
				if ((this._nhaSanXuat != value))
				{
					this.OnnhaSanXuatChanging(value);
					this.SendPropertyChanging();
					this._nhaSanXuat = value;
					this.SendPropertyChanged("nhaSanXuat");
					this.OnnhaSanXuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dvt", DbType="NVarChar(12)")]
		public string dvt
		{
			get
			{
				return this._dvt;
			}
			set
			{
				if ((this._dvt != value))
				{
					this.OndvtChanging(value);
					this.SendPropertyChanging();
					this._dvt = value;
					this.SendPropertyChanged("dvt");
					this.OndvtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sanPham_ctDonHang", Storage="_ctDonHangs", ThisKey="maSP", OtherKey="maSP")]
		public EntitySet<ctDonHang> ctDonHangs
		{
			get
			{
				return this._ctDonHangs;
			}
			set
			{
				this._ctDonHangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="loaiSanPham_sanPham", Storage="_loaiSanPham", ThisKey="maLoai", OtherKey="maLoai", IsForeignKey=true)]
		public loaiSanPham loaiSanPham
		{
			get
			{
				return this._loaiSanPham.Entity;
			}
			set
			{
				loaiSanPham previousValue = this._loaiSanPham.Entity;
				if (((previousValue != value) 
							|| (this._loaiSanPham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._loaiSanPham.Entity = null;
						previousValue.sanPhams.Remove(this);
					}
					this._loaiSanPham.Entity = value;
					if ((value != null))
					{
						value.sanPhams.Add(this);
						this._maLoai = value.maLoai;
					}
					else
					{
						this._maLoai = default(Nullable<int>);
					}
					this.SendPropertyChanged("loaiSanPham");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="taiKhoanTV_sanPham", Storage="_taiKhoanTV", ThisKey="taiKhoan", OtherKey="taiKhoan", IsForeignKey=true)]
		public taiKhoanTV taiKhoanTV
		{
			get
			{
				return this._taiKhoanTV.Entity;
			}
			set
			{
				taiKhoanTV previousValue = this._taiKhoanTV.Entity;
				if (((previousValue != value) 
							|| (this._taiKhoanTV.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._taiKhoanTV.Entity = null;
						previousValue.sanPhams.Remove(this);
					}
					this._taiKhoanTV.Entity = value;
					if ((value != null))
					{
						value.sanPhams.Add(this);
						this._taiKhoan = value.taiKhoan;
					}
					else
					{
						this._taiKhoan = default(string);
					}
					this.SendPropertyChanged("taiKhoanTV");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ctDonHangs(ctDonHang entity)
		{
			this.SendPropertyChanging();
			entity.sanPham = this;
		}
		
		private void detach_ctDonHangs(ctDonHang entity)
		{
			this.SendPropertyChanging();
			entity.sanPham = null;
		}
	}
}
#pragma warning restore 1591
